version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/etc/django/${APP_NAME}/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    command: /bin/sh scripts/start-server.sh
    volumes:
      - mediafiles:/etc/django/${APP_NAME}/mediafiles
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - WEIGHTS_PATH=${WEIGHTS_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - db
volumes:
  mediafiles:
